controllers/AdminpanelController.php
<?php

namespace app\controllers;


use app\models\AnswerQuestion;
use app\models\form\AdminPanelForm;
use Yii;
use yii\web\Controller;
use app\models\activeRecord\Contact;
use yii\data\ActiveDataProvider;


class AdminpanelController extends Controller
{
     public function actionAddTopics()
     {
         //d
         if(Yii::$app->user->isGuest || Yii::$app->user->identity->user_role==0) {
             $this->goHome();
         }
         $model = new AdminPanelForm();
         if ($model->load(Yii::$app->request->post()) && $model->validate()) {
             $model->addNewTopic();
             Yii::$app->session->setFlash("topic_added","Topic: '".$model->topic."' has been added");
         }
         return $this->render('addtopics', [
             'model' => $model,
             ]);
     }
     public function actionRemoveTopics(){
         if(Yii::$app->user->isGuest || Yii::$app->user->identity->user_role==0) {
             $this->goHome();
         }
         $model = new AdminPanelForm();
         if ($model->load(Yii::$app->request->post()) && $model->validate()) {
             if($model->removeTopic()){
                 Yii::$app->session->setFlash("topic_removed","Topic: '".$model->topic."' has been removed");
             }
             else{
                 Yii::$app->session->setFlash("topic_not_removed","Can not remove: '".$model->topic."'. Are you sure it does exist?");
             }
         }
         return $this->render('removetopics', [
             'model' => $model,
         ]);

     }
     public function actionMessages(){
         if(Yii::$app->user->isGuest || Yii::$app->user->identity->user_role==0) {
             $this->goHome();
         }
         $ctc = new Contact();
         $provider = new ActiveDataProvider([
             'query'=> $ctc->find(),
             'pagination' => [
                 'pageSize' => 100,
             ],
         ]);

         return $this->render('messages', [
             'provider'=>$provider,
         ]);
     }
    public function actionDeleterecord($id){
        if(Yii::$app->user->isGuest || Yii::$app->user->identity->user_role==0) {
            $this->goHome();
        }
        $ctc = Contact::find()->where(['ID'=>$id])->one();
        $ctc->delete();
            return $this->render("deleterecord");
    }
    public function actionAnswerQuestion($id){
        if(Yii::$app->user->isGuest || Yii::$app->user->identity->user_role==0) {
            $this->goHome();
        }
        $model = new AnswerQuestion();
        //taking conversation info
        $info = Contact::find()->where(['ID'=>$id])->one();

        if($model->load(Yii::$app->request->post())){
            $model->sendMail($info->email, $info->subject);
            Yii::$app->session->setFlash("email_sent","Email has been sent");
        }

        return $this->render('answerquestion', [
            'info'=>$info,
            'model'=>$model,
        ]);
    }
}

views/adminpanel/addtopics.php
<?php
use yii\helpers\Html;

use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
$this->title = 'Add_Topic';
//$this->params['breadcrumbs'][] = $this->title;
?>
<script src="<?= Yii::getAlias('@web') ?>/js/min-height-image.js"></script>
<div class="site-Add_Topics">
    <h3> <?= Yii::t('app', 'Add new #topic:') ?> </h3>
    <div class="container">
        <div class="col-md-8 cnt-pg">

            <?php $form = ActiveForm::begin([
                'id' => 'add_topics-form',
                'options' => ['class' => 'form-horizontal'],
                'fieldConfig' => [
                    'template' => "{label}<div class=\"col-md-4\">{input}</div>\n<div class=\"col-mg-4\">{error}</div>",
                    'labelOptions' => ['class' => 'col-md-4 control-label'],
                ],
            ]); ?>

            <?= $form->field($model, 'topic')->textInput() ?>


            <div class="form-group">
                <div class="col-lg-offset-4 col-lg-11">
                    <?= Html::submitButton(Yii::t('app', 'Add'), ['class' => 'btn btn-primary', 'name' => 'new_topic-button']) ?>
                </div>
            </div>

            <?php
            if(Yii::$app->session->hasFlash('topic_added'))
                echo "<div class = 'alert alert-success'>" . Yii::$app->session->getFlash('topic_added')." </div>";
            ?>

            <?php ActiveForm::end(); ?>
        </div>
        <div class="col-md-4 cnt-pg image-div" style="background: url('<?= Yii::getAlias('@web') ?>/img/12.jpg');background-size:cover;">

        </div>
    </div>

</div>

views/adminpanel/answerquestion.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use yii\captcha\Captcha;


$this->title = Yii::t('app', 'Answerquestion');
?>
<!doctype html>
<div class="contact_page">
    <h3><?= Yii::t('app', 'Answer question') ?></h3>
    <?php
    if(Yii::$app->session->hasFlash("email_sent"))
        echo "<div class = 'alert alert-success'>" . Yii::$app->session->getFlash("email_sent")." </div>";
    ?>
    <div class="container">
        <div>
          <h4> Subject:</h4>
            <?= $info->subject;?>
        </div>
        <div>
          <h4>Message:</h4>
            <?= $info->body;?>
        </div>
        <div class="col-md-8 cnt-pg">

            <?php $form = ActiveForm::begin([
                'id' => 'answerquestion-form',
                'options' => ['class' => 'form-horizontal'],
                'fieldConfig' => [
                    'template' => "{label}<div class=\"col-md-4\">{input}</div>\n<div class=\"col-mg-4\">{error}</div>",
                    'labelOptions' => ['class' => 'col-md-4 control-label'],
                ],
            ]); ?>
            <?= $form->field($model, 'message_body')->textArea(['rows' => 6]) ?>

            <div class="form-group">
                <div class="col-lg-offset-4 col-lg-11">
                    <?= Html::submitButton(Yii::t('app', 'Send'),['class'=>'btn btn-primary','name' => 'submit-button']);?>
                </div>
            </div>
            <?php ActiveForm::end(); ?>
        </div>

    </div>
</div>

views/adminpanel/deleterecord.php
<?php
use yii\helpers\Html;

?>
<h1>Item has been removed</h1>
<?= Html::a('Go back', ['/adminpanel/messages'], ['class'=>'btn btn-primary']) ?>

views/adminpanel/messages.php
<?php
use yii\helpers\Html;
use yii\grid\GridView;
use yii\data\ActiveDataProvider;
use  yii\data\ArrayDataProvider;
use app\models\Topics;

/* @var $this yii\web\View */
$this->title = Yii::t('app', 'Messages');

?>
<head>
    <link rel="stylesheet" type="text/css" href="<?= Yii::getAlias('@web') ?>/css/contact.css">
</head>

<div class="site-messages" style="text-align: center">
    <h3><?= Html::encode($this->title) ?></h3>
        <div class="dataGridView">
            <?php
                 echo GridView::widget([
                     'dataProvider' => $provider,
                     'columns' => [
                         ['class' => 'yii\grid\SerialColumn',
                             'contentOptions'=>['style'=>'width: 30px;']],
                         //subject
                         [
                             'attribute' => 'subject',
                             'format' => 'text',
                             'label' => 'Subject',
                             'contentOptions'=>['style'=>'width: 10px;']
                         ],
                         //body
                         [
                             'attribute' => 'body',
                             'format' => 'text',
                             'label' => 'Body',
                             'contentOptions' => ['class' => 'text-wrap']
                         ],
                         [
                             'class' => 'yii\grid\ActionColumn',
                             'header'=>Yii::t('app', 'Action'),
                             'headerOptions' => ['width' => '70'],
                             'template' => '{deleterecord}{answerquestion}',
                             'buttons' => [
                                 'deleterecord' => function ($url, $model) {
                                     return Html::a('<span class="fa fa-search"></span>'. Yii::t('app', 'delete'), $url, [
                                         'class'=>'btn btn-primary btn-xs',
                                     ]);
                                 },
                                 'answerquestion' => function ($url, $model) {
                                     return Html::a('<span class="fa fa-search"></span>'. Yii::t('app', 'answer'), $url, [
                                         'class'=>'btn btn-primary btn-xs',
                                     ]);
                                 },
                             ],
                             'urlCreator' => function ($action, $model, $key, $index) {
                                 if ($action ==='deleterecord') {
                                     return Yii::$app->getUrlManager()->createUrl(['adminpanel/'.$action, 'id' => $key]);
                                 }
                                 else if($action === 'answerquestion'){
                                     return Yii::$app->getUrlManager()->createUrl(['adminpanel/'.$action, 'id' => $key]);
                                 }
                                 else {
                                     return Yii::$app->getUrlManager()->createUrl([$action, 'id' => $key]);
                                 }


                             },

                         ],
                     ],
                     'tableOptions' =>['class' => 'table table-striped table-bordered'],
                 ]);
            ?>
    </div>

</div>

views/adminpanel/removetopics.php
<?php
use yii\helpers\Html;

use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
$this->title = 'Remove_Topic';
//$this->params['breadcrumbs'][] = $this->title;
?>
<script src="<?= Yii::getAlias('@web') ?>/js/min-height-image.js"></script>

<div class="site-remove_topics">
    <h3> <?= Yii::t('app', 'Remove #topic:') ?> </h3>
    <div class="container">
        <div class="col-md-8 cnt-pg">
            <?php $form = ActiveForm::begin([
                'id' => 'remove_topics-form',
                'options' => ['class' => 'form-horizontal'],
                'fieldConfig' => [
                    'template' => "{label}<div class=\"col-md-4\">{input}</div>\n<div class=\"col-mg-4\">{error}</div>",
                    'labelOptions' => ['class' => 'col-md-4 control-label'],
                ],
            ]); ?>

            <?= $form->field($model, 'topic')->textInput() ?>


            <div class="form-group">
                <div class="col-lg-offset-4 col-lg-11">
                    <?= Html::submitButton(Yii::t('app', 'Remove'), ['class' => 'btn btn-primary', 'name' => 'remove_topic-button']) ?>
                </div>
            </div>

            <?php
            if(Yii::$app->session->hasFlash('topic_removed'))
                echo "<div class = 'alert alert-success'>" . Yii::$app->session->getFlash('topic_removed')." </div>";
            else if(Yii::$app->session->hasFlash('topic_not_removed'))
                echo "<div class = 'alert alert-danger'>" . Yii::$app->session->getFlash('topic_not_removed')." </div>";
            ?>


            <?php ActiveForm::end(); ?>
        </div>
        <div class="col-md-4 cnt-pg image-div" style="background: url('<?= Yii::getAlias('@web') ?>/img/12.jpg');background-size:cover;">

        </div>
    </div>
</div>